#!/bin/bash

set -e
set -x

download() {
	local src="$1"
	local dst="$2"

	if [ -e /usr/bin/wget ]; then
		wget "${src}" -O "${dst}"
	elif [ -e /usr/bin/curl ]; then
		curl "${src}" -o "${dst}"
	else
		echo 'No available downloader'
		exit 1
	fi
}

# download .vimrc
download 'https://github.com/sigsergv/dotfiles/raw/master/.vimrc' ~/.vimrc

# download and install more-shell-utils
TMP=$(tempfile)
download 'https://github.com/sigsergv/shell-utils/releases/download/1.8/more-shell-utils_1.8-1_all.deb' $TMP
sudo dpkg -i $TMP
rm -f $TMP
