#!/bin/sh

# put this file to the directory /etc/pm/sleep.d/

case "$1" in
	thaw|resume)
	sleep 2

	# force dpms turn off
	sudo -u cancel /home/cancel/hg-stuff/configs/turn-off-dpms

	# restore x keys
	sudo -u cancel /home/cancel/hg-stuff/configs/init-keys.sh
	;;

	*) exit $NA
	;;
esac
