#!/bin/bash
# Assign this script to hotkey X86Tool to toggle touchpad on/off

device=$(xinput list | grep Touchpad | grep -o 'id=[0-9]\+' | grep -o '[0-9]\+')

state=$(xinput list-props $device | grep 'Device Enabled' | grep -o '[01]$')
if [ "$state" = "1"  ]; then
	xinput --disable $device
else
	xinput --enable $device
fi
